UoA-CARES/autonomous_f1tenth

src/reinforcement_learning/config/car_goal.yaml
src/reinforcement_learning/config/car_wall.yaml
src/reinforcement_learning/launch/car_goal.launch.py
src/reinforcement_learning/reinforcement_learning/car_goal_training.py
src/reinforcement_learning/reinforcement_learning/car_wall_training.py

Add configs for the car_wall and car_goal environments

16 configify the autonomous f1tenth package

---

src/environments/environments/CarBlockEnvironment.py
src/environments/environments/CarBlockReset.py
src/environments/environments/util.py
src/environments/launch/carblock.launch.py
src/environments/setup.py
src/reinforcement_learning/config/car_block.yaml
src/reinforcement_learning/launch/car_block.launch.py
src/reinforcement_learning/reinforcement_learning/car_block_training.py
src/reinforcement_learning/setup.py

21 implement carblock

---

src/environments/environments/CarBlockEnvironment.py
src/environments/environments/CarGoalEnvironment.py
src/environments/environments/CarWallEnvironment.py
src/reinforcement_learning/reinforcement_learning/car_block_training.py

Moved the MAX_ACTION/OBSERVATION_SIZE etc inside the environment. This is a precursor to #44. After this, we can write one training loop and just substitute out the environments

28 move the action and observation spaces inside the environment openai gym like

---

src/environments/environments/CarBlockEnvironment.py
src/environments/environments/CarWallEnvironment.py

Fix the inf values for the lidar output

51 lidar is producing inf values

---

src/environment_interfaces/srv/Reset.srv
src/environments/environments/CarBlockEnvironment.py
src/environments/environments/CarBlockReset.py
src/environments/environments/CarTrackParentEnvironment.py
src/environments/environments/CarWallEnvironment.py
src/environments/environments/CarWallReset.py
src/environments/environments/ParentCarEnvironment.py

Changelog:
- Change the request reset parameters
- Parent class for CarBlock, CarWall and CarTrack, but not CarGoal because CarGoal has completely different code which means it will have tons of override methods. So no point to inherit it.

Add parent class for all environments

---

src/reinforcement_learning/config/test.yaml
src/reinforcement_learning/launch/sanity_check.launch.py
src/reinforcement_learning/launch/test.launch.py
src/reinforcement_learning/reinforcement_learning/sanity_check.py
src/reinforcement_learning/reinforcement_learning/test.py
src/reinforcement_learning/reinforcement_learning/train.py

Also modify the launch files for test and sanity

Add namespace to robot description

---

src/environments/environments/CarBeatEnvironment.py

Adds reset publisher to CarBeatEnvironment.

feat: add reset publisher to CarBeat

---

Dockerfile

fixed dockerfile building

---

src/environments/environments/CarTrackEnvironment.py
src/environments/environments/waypoints.py
src/environments/worlds/budapest_track.sdf
src/reinforcement_learning/config/sanity_check.yaml
src/reinforcement_learning/config/train.yaml
src/reinforcement_learning/reinforcement_learning/train.py

Added one lap complete as a termination condition

Fix termination condition

---

src/reinforcement_learning/config/train.yaml
src/reinforcement_learning/reinforcement_learning/train.py

- add evaluation every N steps
- add evaluate for M episodes
- writes to data file
- can configure using train.yaml

feat: add evaluation

---

src/environments/environments/CarBeatEnvironment.py
src/environments/environments/configurations.py
src/reinforcement_learning/reinforcement_learning/parse_args.py
src/reinforcement_learning/reinforcement_learning/train.py
src/reinforcement_learning/reinforcement_learning/training_loops.py

Adds in the pydantic stuff from cares rl. Updated the saving configs

feat: integrate pydantic models into training

---

src/controllers/config/sim.yaml
src/controllers/controllers/sim.py
src/controllers/launch/sim.launch.py
src/controllers/setup.py
src/reinforcement_learning/reinforcement_learning/parse_args.py

Can now run any traditional control methods alone using ros2 launch controllers sim.launch.py

Traditional testing environment working

---

src/controllers/config/sim.yaml
src/controllers/controllers/random.py
src/controllers/controllers/sim.py
src/controllers/launch/sim.launch.py

Can launch Random from sim.launch.py

Random can launch

---

Dockerfile.car
Dockerfile.sim

Program now uses latest cares_rl library

Dockerfiles fixed

---

src/controllers/config/car.yaml
src/controllers/launch/car.launch.py

Can now launch any traditional algorithm on car by editing car.yaml

Car launch

---

src/controllers/config/sim.yaml
src/controllers/controllers/mpc.py
src/controllers/controllers/random.py
src/controllers/controllers/track.py
src/controllers/controllers/turn_and_drive.py
src/controllers/launch/sim.launch.py
src/controllers/setup.py

Fixes issue so instead of having to write a new main function for each algorithm, you just need to create the class

Path track function

---

src/controllers/config/sim.yaml
src/controllers/controllers/pure_pursuit.py
src/controllers/controllers/track.py
src/controllers/launch/sim.launch.py
src/environments/environments/util.py

178 implement pure pursuit

---

.gitmodules

F1Tenth is now based off a forked submodule in CARES. All changes to F1Tenth from now will need to go through that repo

F1tenth submodule

---

src/controllers/config/sim.yaml
src/controllers/controllers/mpc.py
src/controllers/controllers/pure_pursuit.py
src/controllers/controllers/random.py
src/controllers/controllers/track.py
src/controllers/controllers/turn_and_drive.py
src/controllers/controllers/util.py

Turn and drive working version

196 turn and drive on track

---

src/controllers/controllers/track.py
src/controllers/controllers/turn_and_drive.py
src/controllers/controllers/util.py

180 linear speed adjustment

---

src/environments/environments/CarTrackEnvironment.py
src/reinforcement_learning/reinforcement_learning/parse_args.py

- Added lidar points setting on top of the car track environment just to make it easier to change
- Added support for SACAE, might aswell

Lidar processing and progressive reward

---

src/controllers/controllers/planner.py

Dstar working

---

src/controllers/config/plan.yaml
src/controllers/controllers/path_planners/AStar.py
src/controllers/controllers/path_planners/DStarLite.py
src/controllers/controllers/path_planners/ImageGraph.py
src/controllers/controllers/path_planners/PriorityQueue.py
src/controllers/controllers/path_planners/util.py
src/controllers/controllers/planner.py
src/controllers/launch/plan.launch.py
src/controllers/setup.py

Restructured. Can now load in algorithm of choice and map of choice

Improve planner

---

src/controllers/config/sim.yaml
src/controllers/controllers/planner.py

Converts planning coords to odom coords

Odomconvert

---

src/controllers/config/sim.yaml
src/controllers/controllers/path_trackers/mpc.py
src/controllers/controllers/path_trackers/pure_pursuit.py
src/controllers/controllers/planner.py
src/controllers/controllers/track.py

Fixed muticoords issues
Changed direction of planner coords

Directional fixes

---

src/environments/environments/CarBeatEnvironment.py
src/environments/environments/CarBlockEnvironment.py
src/environments/environments/CarGoalEnvironment.py
src/environments/environments/CarTrackEnvironment.py
src/environments/environments/CarWallEnvironment.py
src/reinforcement_learning/reinforcement_learning/EnvironmentFactory.py
src/reinforcement_learning/reinforcement_learning/sanity_check.py

Using config dictionary in environment factory to avoid duplication

Refactoring env factory

---

src/controllers/launch/car.launch.py
src/controllers/launch/sim.launch.py

Some dictionaries that don't do much, might be from old code. If there for a reason, I can revert those changes. Also used .get() method on the config dictionary to return default value of 'f1tenth' if 'car_name' doesn't exist, without the need for the conditionals.

Cleaned up launch files

---

src/environments/environments/CarBeatEnvironment.py
src/environments/environments/CarBlockEnvironment.py
src/environments/environments/CarGoalEnvironment.py
src/environments/environments/CarTrackEnvironment.py
src/environments/environments/CarWallEnvironment.py
src/reinforcement_learning/reinforcement_learning/EnvironmentFactory.py
src/reinforcement_learning/reinforcement_learning/sanity_check.py

Reverts UoA-CARES/autonomous_f1tenth#256

Revert "Refactoring env factory"

---

src/controllers/controllers/controller.py
src/environments/environments/util.py

- FTG now uses the avg_lidar method for generating observations. 
- Controller observation method configuration in controller init.

FTG working version

---

src/reinforcement_learning/config/train.yaml

- Spawns two cars
- Each car creates its own recording files

working with incorrect spawning

---

src/environments/environments/TwoCarEnvironment.py
src/reinforcement_learning/config/train_car2.yaml
src/reinforcement_learning/reinforcement_learning/training_loops.py

- Both training configs needs the correct track info

now spawns correctly

---

src/environments/environments/TwoCarEnvironment.py

Reverts UoA-CARES/autonomous_f1tenth#290

Revert "Refact/simplify two car reward"

---

src/environments/environments/TwoCarEnvironment.py

- Two car environment can now get odometry of both cars for reward function

New get odoms func

---

src/environments/environments/TwoCarEnvironment.py

- Fixed specifically for Two Car. Not sure if this affects other environments.

turning penalty based on steering angle

---

src/environments/environments/CarTrackEnvironment.py

Accidentally forgot to change this environment

Removed changes in spawn location

---

src/environments/environments/TwoCarEnvironment.py

* car spawn func empty
* Car spawning separate func
* Comment logging

Refact/car reset func (#321)

---

src/environments/environments/CarBeatEnvironment.py
src/environments/environments/CarOvertakeEnvironment.py
src/environments/environments/CarRaceEnvironment.py
src/environments/environments/CarTrackEnvironment.py
src/reinforcement_learning/reinforcement_learning/train.py

removed /2 of the spawn location for other environments

removed /2 of spawn location for other envs

---

src/environments/environments/TwoCarEnvironment.py

* Progression vars
* fix index
* Clear debug
* Refactor
* Reward fixes

Bugfix/299 fix two car reward func (#332)
